language: python
dist: xenial # required for Python >= 3.7

python:
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.6"
  - "3.7"

before_install:

  - echo "Installing Ruby..."
  - sudo apt install -y ruby


script:

  - echo "I am script!"