language: python

matrix:

  fast_finish: true

  include:

    - os: linux
      dist: xenial
      python: "3.4"

    - os: linux
      dist: xenial
      python: "3.7"

    - os: osx
      language: generic

addons:
  apt:
    packages:
      - curl
      - build-essential
  homebrew:
    packages:
      - npm
      - mongodb

services:
  - mongodb

before_install:

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew services start mongodb; fi

  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        brew install python;
        virtualenv venv -p python;
        source venv/bin/activate;
      else
        brew install python3;
        virtualenv venv -p python3;
        source venv/bin/activate;
      fi
    fi

  - echo "Decrypting twitter API keys..."
  - openssl aes-256-cbc -K $encrypted_79c27a32ce79_key -iv $encrypted_79c27a32ce79_iv
    -in secrets.json.enc -out ~/secrets.json -d

  - echo "Installing npm..."
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      sudo apt-get install -y nodejs
    fi

script:

  - echo "I am script!"

  - pushd coding

  - echo "Testing twitter fire scraper"
  - pushd twitter-fire-scraper
  - ruby build.rb
  - ruby test-localwheel-install.rb
  - popd

  - echo "Testing twitter fire scraper web API"
  - pushd twitter-fire-scraper-webapi
  - ruby build.rb
  - ruby test-localwheel-install.rb
  - popd

  - echo "twitter-fire-scraper-dashboard"

  - echo "Starting up Web API..."
  - pushd twitter-fire-scraper-webapi
  - pipenv run pip install pip==18.0
  - pipenv install

  - |
    pipenv run python src/twitter_fire_scraper_webapi/app.py 2> /tmp/flask.error.log > /tmp/flask.log & # TODO This is still a race condition. Just one unlikely to fail...
    FLASK_PID=$!
    sleep 30

  - echo PID of flask web server is ${FLASK_PID}
  - curl -v 127.0.0.1:3620
  - popd

  - echo "Starting dashboard..."
  - pushd twitter-fire-scraper-dashboard/TwitterFireScraperDashboard/TwitterFireScraperDashboard
  - npm install
  - npm run build

  - |
    npm run serve 2> /tmp/node.error.log > /tmp/node.log & # TODO This is still a race condition. Just one unlikely to fail...
    NPM_PID=$!
    sleep 30

  - echo PID of node web server is ${NPM_PID}
  - curl -v localhost:3000
  - popd

  - popd

after_failure:

  - echo "Log of twitter-fire-scraper-webapi:"
  - cat /tmp/flask.log

  - echo "Error log of twitter-fire-scraper-webapi:"
  - cat /tmp/flask.error.log


  - echo "Log of twitter-fire-scraper-dashboard:"
  - cat /tmp/node.log

  - echo "Error log of twitter-fire-scraper-dashboard:"
  - cat /tmp/node.error.log