language: python
dist: xenial # required for Python >= 3.7

python:
  - "3.4"
#  - "3.5"
#  - "3.6"
#  - "3.7"
  
services:
  - mongodb

before_install:

  - echo "Decrypting twitter API keys..."
  - openssl aes-256-cbc -K $encrypted_79c27a32ce79_key -iv $encrypted_79c27a32ce79_iv
    -in secrets.json.enc -out ~/secrets.json -d

  - echo "Installing npm..."
  - sudo apt install -y curl
  - sudo apt-get install -y build-essential
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs

script:

  - echo "I am script!"

  - pushd coding

  - echo "Testing twitter fire scraper"
  - pushd twitter-fire-scraper
  - ruby build.rb
  - ruby test-localwheel-install.rb
  - popd

  - echo "Testing twitter fire scraper web API"
  - pushd twitter-fire-scraper-webapi
  - ruby build.rb
  - ruby test-localwheel-install.rb
  - popd

  - echo "twitter-fire-scraper-dashboard"

  - echo "Starting up Web API..."
  - pushd twitter-fire-scraper-webapi
  - pipenv run pip install pip==18.0
  - pipenv install
  - |
    pipenv run python src/twitter_fire_scraper_webapi/app.py&
    FLASK_PID=$!
  - curl localhost:3620
  - popd

  - echo "Starting dashboard..."
  - pushd twitter-fire-scraper-dashboard/TwitterFireScraperDashboard/TwitterFireScraperDashboard
  - npm install
  - npm run build
  - npm run serve &
  - curl localhost:3000
  - popd

  - popd
