language: python
dist: xenial # required for Python >= 3.7

python:
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.6"
  - "3.7"

before_install:

  - echo "Installing npm..."
  - sudo apt install -y npm


script:

  - echo "I am script!"

  - pushd coding

  - echo "twitter-fire-scraper"
  - pushd twitter-fire-scraper

  - ruby build.rb
  - ruby test-localwheel-install.rb
  - popd